// participantesData.js
const participantesData = [
    {
        cedula: "99999999",
        nombre: "Oratorio",
        apellido1: "Bartolomé",
        apellido2: "Garelli",
        fechaNacimiento: "2024-01-01",
        fechaIngreso: "2024-02-02",
        correo: "oratorio@cedesdonbosco.ed.cr",
        telefono: "20202020",
        condicion: "activo",
        residencia: "Alajuelita",
        fk_etapa: null,
    },
    {
        cedula: "88888888",
        nombre: "Sofia",
        apellido1: "Vargas",
        apellido2: "Herrera",
        fechaNacimiento: "1997-08-08",
        fechaIngreso: "2023-08-08",
        correo: "sofia.vargas@example.com",
        telefono: "8888888888",
        condicion: "Alumno",
        residencia: "San Jose",
        fk_etapa: null,
    },
    {
        cedula: "77777777",
        nombre: "Diego",
        apellido1: "Torres",
        apellido2: "Mora",
        fechaNacimiento: "1996-07-07",
        fechaIngreso: "2023-08-07",
        correo: "diego.torres@example.com",
        telefono: "7777777777",
        condicion: "Alumno",
        residencia: "Guanacaste",
        fk_etapa: null,
    },
    {
        cedula: "12345678",
        nombre: "Andres",
        apellido1: "Melendez",
        apellido2: "Carvajal",
        fechaNacimiento: "2023-06-08",
        fechaIngreso: "2023-06-08",
        correo: "abcd@gmail.com",
        telefono: "12345678",
        condicion: "Alumno",
        residencia: "Desampa",
        fk_etapa: null,
    },
    {
        cedula: "12131415",
        nombre: "Santiago",
        apellido1: "Villarreal",
        apellido2: "Arley",
        fechaNacimiento: "2006-11-26",
        fechaIngreso: "2024-05-17",
        correo: "arley@gmail.com",
        telefono: "96959695",
        condicion: "activo",
        residencia: "Santa Ana",
        fk_etapa: null,
    },
    {
        cedula: "119640904",
        nombre: "Juan",
        apellido1: "Pérez",
        apellido2: "González",
        fechaNacimiento: "1990-01-01",
        fechaIngreso: "2024-01-01",
        correo: "juan.perez@example.com",
        telefono: "555-1234",
        condicion: "inactivo",
        residencia: "San José",
        fk_etapa: null,
    },
    {
        cedula: "11111111",
        nombre: "Juan",
        apellido1: "Pérez",
        apellido2: "González",
        fechaNacimiento: "1990-01-01",
        fechaIngreso: "2024-01-01",
        correo: "juan.perez@example.com",
        telefono: "555-1234",
        condicion: "activo",
        residencia: "San José",
        fk_etapa: null,
    }
];

export default participantesData;
